{"name": "test_is_prime_1_5", "status": "failed", "statusDetails": {"message": "AssertionError: True is not false", "trace": "self = <testcase.test_func.TestMyFunc testMethod=test_is_prime_1_5>, a = 5\n\n    @data(5, 7,8,-2,0,1)\n    def test_is_prime(self, a):    #测试用例以test_开头\n        ''' test method is_prime(number) '''\n        print(\"is_prime\")\n>       self.assertFalse(is_prime(a))\nE       AssertionError: True is not false\n\ntestcase\\test_func.py:37: AssertionError"}, "description": " test method is_prime(number) ", "attachments": [{"name": "stdout", "source": "1a2b4da0-31ce-4517-a629-36e6c652f0fb-attachment.txt", "type": "text/plain"}], "start": 1572531712047, "stop": 1572531712047, "uuid": "2bbeba39-e023-413b-ab09-05d01848246a", "historyId": "ec6e6d7817f233fd8513441fd967e7b1", "testCaseId": "770558f79362c4e37c10f46c3f7adc88", "fullName": "testcase.test_func.TestMyFunc#test_is_prime_1_5", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_func"}, {"name": "subSuite", "value": "TestMyFunc"}, {"name": "host", "value": "LeeYatyi"}, {"name": "thread", "value": "12480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_func"}]}